[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_counter_test = "GUh3T2bQtroZ8qH1JpjEYgHaLVqbUosBHffsWd7rcuaE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/sujoynath/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
